apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mealie-deploy
  name: mealie-deploy
  namespace: mealie
spec:
  replicas: 5
  selector:
    matchLabels:
      app: mealie-deploy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mealie-deploy
    spec:
      containers:
      - image: ghcr.io/mealie-recipes/mealie:latest
        name: mealie
        ports:
          - containerPort: 9000
        volumeMounts:
          - mountPath: /app/data
            name: mealie-data
      volumes:
        - name: mealie-data
          persistentVolumeClaim:
            claimName: mealie-data
