apiVersion: v1
kind: Service
metadata:
  labels:
    app: mealie-deploy
  name: mealie-svc
  namespace: mealie
  resourceVersion: "4333527"
  uid: 7bdcb29f-4daa-41a7-b230-d52a4236d243
spec:
  ports:
  - port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: mealie-deploy
  type: LoadBalancer
